export const ADD_VICTIM = 'ADD_VICTIM'
export const REMOVE_VICTIM = 'REMOVE_VICTIM'
export const TARGET_VICTIM = 'TARGET_VICTIM'

export const SET_ATTACKS = 'SET_ATTACKS'
export const TOGGLE_ACTIVE_ATTACK = 'TOGGLE_ACTIVE_ATTACK'
export const UPDATE_ACTIVE_ATTACK_INPUT = 'UPDATE_ACTIVE_ATTACK_INPUT'
export const SET_PENDING_ATTACK_EDITS = 'SET_PENDING_ATTACK_EDITS'

export const SET_LOGGER = 'SET_LOGGER'